name: learn-github-actions
on: [push]
jobs: 
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: echo "This job was automatically trigerred by ${{github.event_name}} event"
    - run: pwd 
    - run: ls -la
